### PR TITLE
Add column widths with table data attribute

### PR DESCRIPTION
**Pull request by jakubfindura**
We needed to add a column widths in HTML template. 

You can supply the column widths in table attribute data-widths.
it's either `<table data-widths="[100,'*','auto']">` or `<table data-widths='[100,"*","auto"]'>`, it will be parsed as JSON. The length of the array must be greater or equal to the number of columns in table.

### CODE REVIEW

**Comment by Aymkdn** [comment]
For this one, I'd like to see if I can make it more general to all other available PDFMake options, instead of only targetting `widths` for `table`.

**Comment by jakubfindura** [comment]
Yes, I'm looking into it too. This was the attribute, which we needed in our case at most.

I've thought about the more generic approach too and will try to implement it.

**Comment by Aymkdn** [comment]
> Yes, I'm looking into it too. This was the attribute, which we needed in our case at most.
> 
> I've thought about the more generic approach too and will try to implement it.

I'm already working on it. I won't have the time to finish it today, but probably tomorrow. I've discovered a bug while working on this feature, and I'm working on that too :-)

**Comment by jakubfindura** [comment]
Okay, I'll wait for it than when it's already WIP :)

**Comment by Aymkdn** [comment]
I've just released v1.2.0 and about the documentation: https://github.com/Aymkdn/html-to-pdfmake#special-properties

**Pull request closed without merging**
